### ISSUE TITLE
are you keeping?

### ISSUE THREAD

**Issue by hhhaiai** [vitrun/qart#4]
hello :
  are you keeping? if you have any need for help, please don't hesitate to contact me.

 sanbo.xyz@gmail#com

**Comment by vitrun** [comment]
@hhhaiai you mean maintaining this repo?

**Comment by rstudiocode** [comment]
Hello
When i want to go on https://research.swtch.com/qr/draw and generate a custom qrcode, I can't : i have this error. How can I do to generate an art qrcode. Can you fix my issue please
![image](https://user-images.githubusercontent.com/63545838/144753823-dd9fac76-5454-4cb7-b18e-bbd2668326ab.png)
